# Form implementation generated from reading ui file 'game_instructions.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_game_instructions_Dialog(object):
    def setupUi(self, game_instructions_Dialog):
        game_instructions_Dialog.setObjectName("game_instructions_Dialog")
        game_instructions_Dialog.resize(875, 659)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=game_instructions_Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 821, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.top_label.setFont(font)
        self.top_label.setObjectName("top_label")
        self.verticalLayout.addWidget(self.top_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.line = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=game_instructions_Dialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 70, 821, 541))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info_Label = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.info_Label.setMaximumSize(QtCore.QSize(800, 16777215))
        self.info_Label.setWordWrap(True)
        self.info_Label.setObjectName("info_Label")
        self.verticalLayout_2.addWidget(self.info_Label)

        self.retranslateUi(game_instructions_Dialog)
        QtCore.QMetaObject.connectSlotsByName(game_instructions_Dialog)

    def retranslateUi(self, game_instructions_Dialog):
        _translate = QtCore.QCoreApplication.translate
        game_instructions_Dialog.setWindowTitle(_translate("game_instructions_Dialog", "Dialog"))
        self.top_label.setText(_translate("game_instructions_Dialog", "Peliohjeet"))
        self.info_Label.setText(_translate("game_instructions_Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Pelin idea</span></p><p>Tämän pelin idea sai alkunsa siitä havainnosta, että suuret kielimallit, kuten ChatGPT, eivät osaa tuottaa palindromeja. Kielimallien vahvuus on sanojen todennäköisyyksien ymmärtämisessä, mutta palindromeissa vaadittava symmetria ei kuulu niiden osaamiseen. Pelin tavoitteena on oppia, kuinka löytää sopiva ennustemalli ja toteuttaa palindromigeneraattori symmetriasääntöjen avulla.</p><p><span style=\" font-weight:600;\">Pelimekaniikka</span></p><p>Peli sisältää valmiiksi generoituja lyhyitä palindromeja, joita voit yrittää löytää ja jatkaa. Jos onnistut keksimään uuden palindromin, saat 1000 pistettä. Löytäessäsi jo tunnetun palindromin, saat 10 pistettä. Tässä vaiheessa palindromin pituudella ei ole vaikutusta pisteisiin, eikä uudet löydetyt palindromit tallennu mihinkään.</p><p><span style=\" font-weight:600;\">Näin aloitat</span></p><p>Kirjoita ensimmäinen sana vasempaan tekstikenttään ja jatka siitä eteenpäin. Voit myös &quot;luntata&quot; aiemmin löydettyjä palindromeja, mutta jos käytät niitä suoraan, et ansaitse pisteitä. Voit kokeilla liittää pidempiä palindromeja yhteen käyttämällä symmetrisiä sanoja, kuten &quot;ISI&quot;, palindromin molemmissa päissä.</p><p><span style=\" font-weight:600;\">Vinkki</span></p><p>Täysin uuden palindromin tuottaminen voi onnistua peilaamalla sanoja vasemmalta oikealle ja kokeilemalla, mikä sana tai kirjain keskellä tuottaisi palindromin. Muista kuitenkin, että jotta palindromi olisi järkevä, kaikkien sen sanojen tulisi löytyä sanakirjasta!</p><p><span style=\" font-weight:600; font-style:italic;\">Onnea uusien palindromien metsästykseen!</span></p></body></html>"))
