# Form implementation generated from reading ui file 'graph_visualization.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_graph_Dialog(object):
    def setupUi(self, graph_Dialog):
        graph_Dialog.setObjectName("graph_Dialog")
        graph_Dialog.resize(903, 751)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(graph_Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graph_layout = QtWidgets.QVBoxLayout()
        self.graph_layout.setObjectName("graph_layout")
        self.verticalLayout_2.addLayout(self.graph_layout)

        self.retranslateUi(graph_Dialog)
        QtCore.QMetaObject.connectSlotsByName(graph_Dialog)

    def retranslateUi(self, graph_Dialog):
        _translate = QtCore.QCoreApplication.translate
        graph_Dialog.setWindowTitle(_translate("graph_Dialog", "Dialog"))
