# Form implementation generated from reading ui file 'inspect_palindromes.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_inspect_Dialog(object):
    def setupUi(self, inspect_Dialog):
        inspect_Dialog.setObjectName("inspect_Dialog")
        inspect_Dialog.resize(556, 672)
        self.gridLayout = QtWidgets.QGridLayout(inspect_Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_label = QtWidgets.QLabel(parent=inspect_Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.top_label.setFont(font)
        self.top_label.setObjectName("top_label")
        self.verticalLayout.addWidget(self.top_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.input_word_lineEdit = QtWidgets.QLineEdit(parent=inspect_Dialog)
        self.input_word_lineEdit.setObjectName("input_word_lineEdit")
        self.horizontalLayout_3.addWidget(self.input_word_lineEdit, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.found_label = QtWidgets.QLabel(parent=inspect_Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.found_label.setFont(font)
        self.found_label.setObjectName("found_label")
        self.horizontalLayout_3.addWidget(self.found_label, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.found_lcdNumber = QtWidgets.QLCDNumber(parent=inspect_Dialog)
        self.found_lcdNumber.setObjectName("found_lcdNumber")
        self.horizontalLayout_3.addWidget(self.found_lcdNumber, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.palindromes_listView = QtWidgets.QListView(parent=inspect_Dialog)
        self.palindromes_listView.setObjectName("palindromes_listView")
        self.horizontalLayout.addWidget(self.palindromes_listView)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(inspect_Dialog)
        QtCore.QMetaObject.connectSlotsByName(inspect_Dialog)

    def retranslateUi(self, inspect_Dialog):
        _translate = QtCore.QCoreApplication.translate
        inspect_Dialog.setWindowTitle(_translate("inspect_Dialog", "Dialog"))
        self.top_label.setText(_translate("inspect_Dialog", "Palindromien tarkastelu"))
        self.input_word_lineEdit.setText(_translate("inspect_Dialog", "Kirjoita ..."))
        self.found_label.setText(_translate("inspect_Dialog", "Löytyi:"))
